title: My Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: your-twitter-handle
github_username:  your-github-handle

# Build settings
markdown: kramdown

theme: minima

header_pages:
  - about.md
  - portfolio.md

# Enable excerpts on the home page
show_excerpts: true

# Disqus integration
disqus:
  shortname: your-disqus-shortname

# Google Analytics integration
google_analytics: UA-NNNNNNNN-N
